version: 0.2

env:
  variables:
    BUCKET: pipelines-for-lambda
    JAVA_VERSION: corretto11
    TEMPLATE_OUT_FILE_NAME: template-out.yaml

phases:
  install:
    runtime-versions:
        java: $JAVA_VERSION
  build:
    commands:
      - mvn clean package
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file $TEMPLATE_OUT_FILE_NAME
artifacts:
  files:
    - $TEMPLATE_OUT_FILE_NAME